### ISSUE TITLE
CMD报Fail to access的错误

### ISSUE THREAD

**Issue by taochongwh** [Threezh1/JSFinder#13]
大佬您好，在爬取某URL时，CMD窗口报Fail to access错误

Fail to access http://www.abc.cn/

大佬可以解释一下吗

**Comment by Threezh1** [comment]
我访问这个网址返回的状态是404，是不是因为网站不能访问的缘故？

**Comment by xxsmile123** [comment]
这个有的时候突然就不能用了，就算网站是正常的。开发大佬能解决一下问题吗。

**Comment by Threezh1** [comment]
出现这种情况一般都是网络的问题，没有具体场景我也没法修复。

**Comment by gayhub-blackerie** [comment]
have a try with your network proxy, turn off it

**Comment by ghost** [comment]
> have a try with your network proxy, turn off it

fine
