### ISSUE TITLE
参数型URL无法提取

### ISSUE THREAD

**Issue by geeeez** [Threezh1/JSFinder#15]
有些网站是需要提供参数的在问号后面 才能展示对应的页面 类似：http://11.1.1.11/123.html?tas=pwd ，但是这样的url 脚本报错
no matches found: http://11.1.1.11/123.html?tas=pwd

**Comment by Threezh1** [comment]
请尝试用双引号包裹参数值。

`jsfinder -u "http://11.1.1.11/123.html\?tas\=pwd"`
