### ISSUE TITLE
无法识别参数

### ISSUE THREAD

**Issue by k0njac** [Threezh1/JSFinder#16]
python .\JSFinder.py -u https://security.shuidihuzhu.com -ou sdcUrl.txt -os sucSubc.txt  -d
 python .\JSFinder.py -u https://security.shuidihuzhu.com -d
 python .\JSFinder.py -u https://security.shuidihuzhu.com 
![image](https://user-images.githubusercontent.com/72721956/107873273-4f7f1d80-6eec-11eb-92b7-eb555f316686.png)

**Comment by Threezh1** [comment]
并不是因为无法识别参数导致没有进行深度爬取，具体原因请再看一下深度爬取的逻辑。

获取页面上所有的url=>再进行接口提取。

你所提供这个链接页面源码中没有a标签，所以深度爬取并没有显示内容。
