### ISSUE TITLE
域名结果显示有问题

### ISSUE THREAD

**Issue by notwhy** [Threezh1/JSFinder#2]
域名结果建议用正则过滤一下
![image](https://user-images.githubusercontent.com/11815957/59401524-8de64000-8dcd-11e9-8ead-e646013c9c66.png)
如oim.oppo.comrightwindowJump.jsp
应该为oim.oppo.com

**Comment by Threezh1** [comment]
域名匹配那还有一些问题，后面解决。

**Comment by Threezh1** [comment]
已经解决。
