### ISSUE TITLE
parse模块已安装仍然提示没有

### ISSUE THREAD

**Issue by z7701858** [Threezh1/JSFinder#5]
Traceback (most recent call last):
  File "JSFinder.py", line 8, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

**Comment by Threezh1** [comment]
安装错了。

**Comment by z7701858** [comment]
pip install parse是这样吗？

**Comment by Amzza0x00** [comment]
python3下运行

**Comment by Curta7n** [comment]
python3缺少bs4.安装后还是提示找不到。python2可以跑吗。应该安装的是哪个parse？

**Comment by Threezh1** [comment]
不知道你那边的具体环境，检查一下是否安装正确。pip 可能安装到python3了。可以再用pip3试一下。

**Comment by Curta7n** [comment]
@Threezh1 
python3的环境
`➜  ~ pip3 list
Package        Version
-------------- ---------
beautifulsoup4 4.8.0
certifi        2019.6.16
chardet        3.0.4
gevent         1.4.0
greenlet       0.4.15
idna           2.8
lxml           4.4.1
pip            19.1.1
progressbar2   3.43.1
python-utils   2.3.0
requests       2.22.0
setuptools     41.0.1
six            1.12.0
soupsieve      1.9.3
urllib3        1.25.3
wheel          0.33.4
➜  ~ cd Tools/information/JSFinder
➜  JSFinder python3 --version
Python 3.7.4
➜  JSFinder python3 JSFinder.py
Traceback (most recent call last):
  File "JSFinder.py", line 9, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
`
python2的环境
`➜  JSFinder pip list
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Package                                Version
-------------------------------------- ---------
altgraph                               0.10.2
bdist-mpkg                             0.5.0
bonjour-py                             0.3
certifi                                2019.6.16
chardet                                3.0.4
dnspython                              1.16.0
gevent                                 1.4.0
greenlet                               0.4.15
idna                                   2.8
ipaddress                              1.0.22
lxml                                   4.4.1
macholib                               1.5.1
matplotlib                             1.3.1
modulegraph                            0.10.4
numpy                                  1.8.0rc1
parse                                  1.12.1
➜  JSFinder python --version
Python 2.7.10
➜  JSFinder python JSFinder.py
Traceback (most recent call last):
  File "JSFinder.py", line 8, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse`

**Comment by Amzza0x00** [comment]
> @Threezh1
> python3的环境
> `➜ ~ pip3 list
> Package Version
> 
> beautifulsoup4 4.8.0
> certifi 2019.6.16
> chardet 3.0.4
> gevent 1.4.0
> greenlet 0.4.15
> idna 2.8
> lxml 4.4.1
> pip 19.1.1
> progressbar2 3.43.1
> python-utils 2.3.0
> requests 2.22.0
> setuptools 41.0.1
> six 1.12.0
> soupsieve 1.9.3
> urllib3 1.25.3
> wheel 0.33.4
> ➜ ~ cd Tools/information/JSFinder
> ➜ JSFinder python3 --version
> Python 3.7.4
> ➜ JSFinder python3 JSFinder.py
> Traceback (most recent call last):
> File "JSFinder.py", line 9, in 
> from bs4 import BeautifulSoup
> ModuleNotFoundError: No module named 'bs4'
> `python2的环境`➜ JSFinder pip list
> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
> Package Version
> 
> altgraph 0.10.2
> bdist-mpkg 0.5.0
> bonjour-py 0.3
> certifi 2019.6.16
> chardet 3.0.4
> dnspython 1.16.0
> gevent 1.4.0
> greenlet 0.4.15
> idna 2.8
> ipaddress 1.0.22
> lxml 4.4.1
> macholib 1.5.1
> matplotlib 1.3.1
> modulegraph 0.10.4
> numpy 1.8.0rc1
> parse 1.12.1
> ➜ JSFinder python --version
> Python 2.7.10
> ➜ JSFinder python JSFinder.py
> Traceback (most recent call last):
> File "JSFinder.py", line 8, in 
> from urllib.parse import urlparse
> ImportError: No module named parse`

python3 -m pip install bs4
安装下就ok了
