### ISSUE TITLE
可以添加批量测试url功能吗？

### ISSUE THREAD

**Issue by zglaozhu** [Threezh1/JSFinder#6]
可以添加批量测试url功能吗

**Comment by Threezh1** [comment]
有批量测试url的。 

指定URL：
python JSFinder.py -f text.txt

指定JS：
python JSFinder.py -f text.txt -j

可以用brupsuite爬取网站后提取出URL或者JS链接，保存到txt文件中，一行一个。

指定URL或JS就不需要加深度爬取，单个页面即可。

**Comment by zglaozhu** [comment]
谢谢啦
